services:
  postgres:
    container_name: app-db
    image: postgres:17.4-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: app-pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
